# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PublishModule < Formula
  desc ""
  homepage ""
  version "0.9.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cinema8150/publish_module/releases/download/v0.9.7/publish_module_Darwin_arm64.tar.gz?private_token=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", using: CurlDownloadStrategy
      sha256 "6635f46c6810b32bb60038f28696e20749d317f7dadca47baaca7d36e00bc54f"

      def install
        bin.install "publish-module"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cinema8150/publish_module/releases/download/v0.9.7/publish_module_Darwin_x86_64.tar.gz?private_token=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", using: CurlDownloadStrategy
      sha256 "527a5eb6687b74398d1bc558509808de3f52957cb8d7cfd502b1fc455575d472"

      def install
        bin.install "publish-module"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cinema8150/publish_module/releases/download/v0.9.7/publish_module_Linux_arm64.tar.gz?private_token=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", using: CurlDownloadStrategy
      sha256 "66de58b01811696bdda324b6d1bf94652461f7eb13631709abfb50e4ea1d9a69"

      def install
        bin.install "publish-module"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cinema8150/publish_module/releases/download/v0.9.7/publish_module_Linux_x86_64.tar.gz?private_token=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", using: CurlDownloadStrategy
      sha256 "5facebcb280cb6de53d3a40b995d87f9045fa03b11d301195e7cb07959d6c51b"

      def install
        bin.install "publish-module"
        # ...
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end
end
